if has('unix')
  let vimFolder = expand('~/.vim')
elseif has('nvim')
  let vimFolder = stdpath('data').'/plugged'
else
  let vimFolder = expand('~/vimfiles')
endif

" {{{ VIM PLUG
" }}}

" {{{ PLUGINS SETTINGS
" }}}

" {{{ VIM OPTIONS

" When in doubt call :help.
" Vim doesn't like keyboard layouts other than US-International, e.g. jumping
" through help tags is mapped with [c-ç] on a ABNT layout.
set modeline

if has('vms')
  set nobackup " VMs have their own backup settings.
else
  if !isdirectory(vimFolder.'/backupdir')
    call mkdir(vimFolder.'/backupdir')
  endif

  if !isdirectory(vimFolder.'/swpdir')
    call mkdir(vimFolder.'/swpdir')
  endif

  set backup
  let &backupdir = vimFolder.'/backupdir'
  let &directory = vimFolder.'/swpdir'

  if has('persistent_undo')
    if !isdirectory(vimFolder.'/undodir')
      call mkdir(vimFolder.'/undodir')
    endif

    set undofile
    let &undodir = vimFolder.'/undodir'
  endif
endif

if has('folding')
  set foldenable
  set foldmethod=indent
  set foldlevelstart=10
  set foldnestmax=10
endif

" }}}

" {{{ VIM VARIABLES
" }}}

" {{{ MY FUNCTIONS
" }}}

" {{{ AUTOCMDS
" }}}

" MAPPINGS {{{

nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>

" }}}

" vim: foldmethod=marker: foldlevel=0
