if has('unix')
  let vimFolder = expand('~/.vim')
elseif has('nvim')
  let vimFolder = stdpath('data').'/plugged'
else
  let vimFolder = expand('~/vimfiles')
endif

" {{{ VIM PLUG

let vimPlugFile = vimFolder.'/autoload/plug.vim'

if empty(glob(vimPlugFile))
  silent execute '!curl -fLo '.vimPlugFile --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin(vimFolder.'/plugged')
  " vim-plug help tags
  Plug 'junegunn/vim-plug'
call plug#end()

" }}}

" {{{ PLUGINS SETTINGS
" }}}

" {{{ VIM OPTIONS

" When in doubt call :help.
" Vim doesn't like keyboard layouts other than US-International, e.g. jumping
" through help tags is mapped with [c-ç] on a ABNT layout.

filetype plugin indent on
set modeline

set expandtab
set tabstop=2
set shiftwidth=2
set shiftround
let mapleader=','
set colorcolumn=81 textwidth=80
set showcmd
set ruler
set number
set relativenumber
set cursorline
set incsearch
set showmatch
set backspace=indent,eol,start,
set path+=**
set wildmenu

if has('vms')
  set nobackup " VMs have their own backup settings.
else
  if !isdirectory(vimFolder.'/backupdir')
    call mkdir(vimFolder.'/backupdir')
  endif

  if !isdirectory(vimFolder.'/swpdir')
    call mkdir(vimFolder.'/swpdir')
  endif

  set backup
  let &backupdir = vimFolder.'/backupdir'
  let &directory = vimFolder.'/swpdir'

  if has('persistent_undo')
    if !isdirectory(vimFolder.'/undodir')
      call mkdir(vimFolder.'/undodir')
    endif

    set undofile
    let &undodir = vimFolder.'/undodir'
  endif
endif

if has('folding')
  set foldenable
  set foldmethod=indent
  set foldlevelstart=10
  set foldnestmax=10
endif

" }}}

" {{{ VIM VARIABLES
" }}}

" {{{ MY FUNCTIONS
" }}}

" {{{ AUTOCMDS
" }}}

" MAPPINGS {{{

nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <c-c> <esc>

nnoremap <leader><space> :nohls<CR>
nnoremap <leader>ev :sp $MYVIMRC<CR>
nnoremap <leader>sv :source $MYVIMRC <bar> :doautocmd BufRead<CR>

nnoremap <space> za

if has('clipboard')
  vnoremap <c-c> "+y<esc>
  vnoremap <c-v> v"+p<esc>
endif

" }}}

" vim: foldmethod=marker: foldlevel=0
